"use client";

import { useEffect, useState } from "react";
import AppShell from "../../components/AppShell";
import { EngagementChart, FollowersGrowthChart } from "../../components/Charts";
import { api } from "../../lib/api";

export default function DashboardPage() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    async function load() {
      try {
        setLoading(true);
        const response = await api.dashboardAnalytics();
        setData(response);
      } catch (err) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    }

    load();
  }, []);

  const engagementChartData = (data?.charts?.engagementComparison || []).map((item) => ({
    ...item,
    displayName: `${item.creatorName} (${item.platform})`
  }));

  const platformSummary = Object.values(
    (data?.charts?.engagementComparison || []).reduce((acc, item) => {
      if (!acc[item.platform]) {
        acc[item.platform] = {
          platform: item.platform,
          creators: 0,
          totalEngagementRate: 0
        };
      }

      acc[item.platform].creators += 1;
      acc[item.platform].totalEngagementRate += Number(item.engagementRate || 0);
      return acc;
    }, {})
  ).map((item) => ({
    ...item,
    averageEngagementRate: item.creators ? item.totalEngagementRate / item.creators : 0
  }));

  return (
    <AppShell>
      {() => (
        <div className="space-y-6">
          <div>
            <h2 className="text-2xl font-bold text-slate-900">Dashboard</h2>
            <p className="text-sm text-slate-600">Overview of creator analytics generated by backend services.</p>
          </div>

          {error ? <p className="text-sm text-rose-600">{error}</p> : null}

          {loading ? <p className="text-slate-600">Loading analytics...</p> : null}

          {data ? (
            <>
              <div className="grid gap-4 md:grid-cols-3">
                <div className="card">
                  <p className="text-sm text-slate-500">Total Creators</p>
                  <p className="mt-2 text-3xl font-bold">{data.totals.totalCreators}</p>
                </div>
                <div className="card">
                  <p className="text-sm text-slate-500">Total Followers</p>
                  <p className="mt-2 text-3xl font-bold">{data.totals.totalFollowers.toLocaleString()}</p>
                </div>
                <div className="card">
                  <p className="text-sm text-slate-500">Avg Engagement Rate</p>
                  <p className="mt-2 text-3xl font-bold">{data.totals.averageEngagementRate}%</p>
                </div>
              </div>

              <div className="grid gap-4 lg:grid-cols-2">
                <FollowersGrowthChart data={data.charts.followersGrowth || []} />
                <EngagementChart data={engagementChartData} />
              </div>

              <div className="card">
                <h3 className="text-base font-semibold">Platform Summary</h3>
                <div className="mt-3 overflow-x-auto">
                  <table className="min-w-full text-sm">
                    <thead>
                      <tr className="border-b border-slate-200 text-left text-slate-600">
                        <th className="py-2 pr-4">Platform</th>
                        <th className="py-2 pr-4">Creators</th>
                        <th className="py-2 pr-4">Avg Engagement</th>
                      </tr>
                    </thead>
                    <tbody>
                      {platformSummary.map((item) => (
                        <tr key={item.platform} className="border-b border-slate-100">
                          <td className="py-2 pr-4">{item.platform}</td>
                          <td className="py-2 pr-4">{item.creators}</td>
                          <td className="py-2 pr-4">{item.averageEngagementRate.toFixed(2)}%</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            </>
          ) : null}
        </div>
      )}
    </AppShell>
  );
}
