"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import AppShell from "../../components/AppShell";
import { api } from "../../lib/api";

const MAX_FILE_SIZE = 5 * 1024 * 1024;
const ACCEPTED_TYPES = ["image/jpeg", "image/png", "image/webp"];

const initialForm = {
  id: null,
  name: "",
  platform: "Instagram",
  username: "",
  profile_image_url: ""
};

export default function CreatorsPage() {
  const fileInputRef = useRef(null);
  const [form, setForm] = useState(initialForm);
  const [creators, setCreators] = useState([]);
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const [file, setFile] = useState(null);
  const [fileError, setFileError] = useState("");
  const [preview, setPreview] = useState("");

  const editing = Boolean(form.id);

  const platforms = useMemo(() => ["Instagram", "YouTube", "X"], []);

  useEffect(() => {
    async function loadCreators() {
      try {
        setLoading(true);
        const res = await api.listCreators();
        setCreators(res.creators || []);
      } catch (err) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    }

    loadCreators();
  }, []);

  useEffect(() => {
    if (!file) {
      setPreview("");
      return;
    }

    const objectUrl = URL.createObjectURL(file);
    setPreview(objectUrl);

    return () => {
      URL.revokeObjectURL(objectUrl);
    };
  }, [file]);

  const resetForm = () => {
    setForm(initialForm);
    setFile(null);
    setPreview("");
    setFileError("");
    if (fileInputRef.current) {
      fileInputRef.current.value = "";
    }
  };

  const refreshList = async () => {
    const res = await api.listCreators();
    setCreators(res.creators || []);
  };

  const handleChange = (event) => {
    setForm((prev) => ({ ...prev, [event.target.name]: event.target.value }));
  };

  const handleFileChange = (event) => {
    setFileError("");
    const selected = event.target.files?.[0];

    if (!selected) {
      setFile(null);
      return;
    }

    if (!ACCEPTED_TYPES.includes(selected.type)) {
      setFileError("Image must be JPG, PNG, or WEBP.");
      setFile(null);
      return;
    }

    if (selected.size > MAX_FILE_SIZE) {
      setFileError("Image must be 5MB or smaller.");
      setFile(null);
      return;
    }

    setFile(selected);
  };

  const handleSubmit = async (event) => {
    event.preventDefault();
    setError("");
    setMessage("");

    if (!form.name.trim() || !form.username.trim()) {
      setError("Creator name and username are required.");
      return;
    }

    if (fileError) {
      setError(fileError);
      return;
    }

    try {
      setSubmitting(true);

      let imageUrl = form.profile_image_url || "";

      if (file) {
        const uploadRes = await api.uploadCreatorImage(file);
        imageUrl = uploadRes.imageUrl;
      }

      const payload = {
        name: form.name.trim(),
        platform: form.platform,
        username: form.username.trim(),
        profile_image_url: imageUrl || null
      };

      if (editing) {
        await api.updateCreator(form.id, payload);
        setMessage("Creator updated successfully.");
      } else {
        await api.createCreator(payload);
        setMessage("Creator added successfully.");
      }

      await refreshList();
      resetForm();
    } catch (err) {
      setError(err.message);
    } finally {
      setSubmitting(false);
    }
  };

  const handleEdit = (creator) => {
    setForm({
      id: creator.id,
      name: creator.name,
      platform: creator.platform,
      username: creator.username,
      profile_image_url: creator.profile_image_url || ""
    });
    setFile(null);
    setPreview(creator.profile_image_url || "");
    setFileError("");
    setMessage("");
    if (fileInputRef.current) {
      fileInputRef.current.value = "";
    }
  };

  const handleDelete = async (creatorId) => {
    setError("");
    setMessage("");

    try {
      await api.deleteCreator(creatorId);
      setMessage("Creator deleted successfully.");
      await refreshList();
      if (form.id === creatorId) {
        resetForm();
      }
    } catch (err) {
      setError(err.message);
    }
  };

  return (
    <AppShell>
      {() => (
        <div className="space-y-6">
          <div>
            <h2 className="text-xl font-bold text-slate-900 sm:text-2xl">Creators</h2>
            <p className="text-sm text-slate-600">
              Add identity fields only. Analytics are generated by backend automatically.
            </p>
          </div>

          <div className="card">
            <h3 className="text-lg font-semibold">{editing ? "Edit Creator" : "Add Creator"}</h3>

            <form className="mt-4 grid gap-4 md:grid-cols-2" onSubmit={handleSubmit}>
              <div>
                <label className="label" htmlFor="name">
                  Creator Name
                </label>
                <input id="name" name="name" className="input" value={form.name} onChange={handleChange} />
              </div>

              <div>
                <label className="label" htmlFor="platform">
                  Platform
                </label>
                <select id="platform" name="platform" className="input" value={form.platform} onChange={handleChange}>
                  {platforms.map((platform) => (
                    <option key={platform} value={platform}>
                      {platform}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="label" htmlFor="username">
                  Username / Handle
                </label>
                <input id="username" name="username" className="input" value={form.username} onChange={handleChange} />
              </div>

              <div>
                <label className="label" htmlFor="image">
                  Profile Image
                </label>
                <input
                  id="image"
                  name="image"
                  type="file"
                  accept="image/png,image/jpeg,image/webp"
                  className="w-full text-sm"
                  ref={fileInputRef}
                  onChange={handleFileChange}
                />
                <p className="mt-1 text-xs text-slate-500">Allowed: JPG, PNG, WEBP. Max size: 5MB.</p>
              </div>

              <div className="md:col-span-2">
                {preview ? (
                  <img
                    src={preview}
                    alt="Preview"
                    className="h-24 w-24 rounded-lg border border-slate-200 object-cover"
                  />
                ) : null}
              </div>

              {fileError ? <p className="text-sm text-rose-600 md:col-span-2">{fileError}</p> : null}
              {error ? <p className="text-sm text-rose-600 md:col-span-2">{error}</p> : null}
              {message ? <p className="text-sm text-emerald-700 md:col-span-2">{message}</p> : null}

              <div className="flex flex-col gap-2 sm:flex-row md:col-span-2">
                <button type="submit" className="btn-primary w-full sm:w-auto" disabled={submitting}>
                  {submitting ? "Saving..." : editing ? "Update Creator" : "Add Creator"}
                </button>
                {editing ? (
                  <button type="button" className="btn-secondary w-full sm:w-auto" onClick={resetForm}>
                    Cancel edit
                  </button>
                ) : null}
              </div>
            </form>
          </div>

          <div className="card overflow-x-auto">
            <h3 className="text-lg font-semibold">Creator List</h3>
            {loading ? <p className="mt-3 text-slate-600">Loading creators...</p> : null}

            {!loading ? (
              <table className="mt-4 min-w-[760px] table-fixed text-sm">
                <thead>
                  <tr className="border-b border-slate-200 text-left text-slate-600">
                    <th className="w-[240px] py-2 pr-4">Creator</th>
                    <th className="w-[110px] py-2 pr-4">Platform</th>
                    <th className="w-[160px] py-2 pr-4">Username</th>
                    <th className="w-[120px] py-2 pr-4">Followers</th>
                    <th className="w-[120px] py-2 pr-4">Engagement</th>
                    <th className="w-[190px] py-2 pr-4">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {creators.map((creator) => (
                    <tr key={creator.id} className="border-b border-slate-100">
                      <td className="py-2 pr-4">
                        <div className="flex min-w-0 items-center gap-2">
                          {creator.profile_image_url ? (
                            <img
                              src={creator.profile_image_url}
                              alt={creator.name}
                              className="h-8 w-8 rounded-full object-cover"
                            />
                          ) : (
                            <div className="h-8 w-8 rounded-full bg-slate-200" />
                          )}
                          <span className="truncate" title={creator.name}>
                            {creator.name}
                          </span>
                        </div>
                      </td>
                      <td className="py-2 pr-4">{creator.platform}</td>
                      <td className="truncate py-2 pr-4" title={creator.username}>
                        {creator.username}
                      </td>
                      <td className="py-2 pr-4">{creator.followers ? Number(creator.followers).toLocaleString() : "-"}</td>
                      <td className="py-2 pr-4">
                        {creator.engagement_rate ? `${Number(creator.engagement_rate).toFixed(2)}%` : "-"}
                      </td>
                      <td className="py-2 pr-4">
                        <div className="flex gap-2">
                          <Link href={`/creators/${creator.id}`} className="btn-secondary px-3 py-1 text-xs">
                            View
                          </Link>
                          <button
                            type="button"
                            className="btn-secondary px-3 py-1 text-xs"
                            onClick={() => handleEdit(creator)}
                          >
                            Edit
                          </button>
                          <button
                            type="button"
                            className="rounded-lg border border-rose-300 px-3 py-1 text-xs font-semibold text-rose-700 hover:bg-rose-50"
                            onClick={() => handleDelete(creator.id)}
                          >
                            Delete
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            ) : null}
          </div>
        </div>
      )}
    </AppShell>
  );
}
